language: android
jdk: oraclejdk7

android:
  components:
    - build-tools-21.0.2
    - android-21
    - extra-android-support
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository

install:
   - TERM=dumb
   
       
script:
    - ./test_script.sh
    
licences:
    - /android-sdk-license-[0-9a-f]{8}/
    
notifications:
    hipchat:
        rooms:
            secure: ZnZVAGmU66mz9QV28qrq0tNagYV7/lxQmsPQg6GlkvM+UVZtb2CTtqEylPYcG12N9c50yY987Kh8dccps2lH14bEcr5uQSvlB/vD2C2hKL+VzwtQ2jTMY2Sf9cJlQwtKaBIkioZCvOiFL3u5tZkKZWxmgziH896ebYdV04otiLU=
        template:
            - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
            
cache:
    directories:
    - /home/travis/.gradle/caches/
    - /home/travis/.gradle/wrapper/dists/gradle-1.12-all/
    - /home/travis/.m2/repository/
